uploads = []
outputs = []

[[generated]]
id = "R7VaPnBRpWOSKpv-3Oqvc"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ld40Q7_80BEHrrRD-IA0h"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
